// <auto-generated />
namespace UMS_Final_Project1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v6u41 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v6u41));
        
        string IMigrationMetadata.Id
        {
            get { return "201412061635298_v6u41"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
